# Pandas 한번에 제대로 배우기




---



In [141]:
import numpy as np
import pandas as pd
pd.__version__

'1.3.5'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = ['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [7]:
s['c']

0.5

In [8]:
s[['c', 'e', 'd']]

c    0.50
e    1.00
d    0.75
dtype: float64

In [9]:
'b' in s

True

In [10]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
              index = [2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [11]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [12]:
s.unique() #unique한 값만 출력

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
1.00    1
dtype: int64

In [14]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [15]:
pop_tuple = {'서울특별시': 9706240,
             '부산광역시': 1000200,
             '인천광역시': 1224320,
             '대구광역시': 2838490,
             '대전광역시': 1833340,
             '광주광역시': 1000020}
population = pd.Series(pop_tuple)
population

서울특별시    9706240
부산광역시    1000200
인천광역시    1224320
대구광역시    2838490
대전광역시    1833340
광주광역시    1000020
dtype: int64

In [16]:
population['서울특별시']

9706240

In [17]:
population['서울특별시':'인천광역시']

서울특별시    9706240
부산광역시    1000200
인천광역시    1224320
dtype: int64

### DataFrame 객체

In [18]:
pd.DataFrame({'A':2, 'B':4, 'D':3}, {'A':4, 'B':3, 'C':7})


A  B  D
A  2  4  3
B  2  4  3
C  2  4  3

In [19]:
pd.DataFrame(np.random.rand(5,5),
             columns=['A', 'B', 'C', 'D', 'E'],
             index=[1,2,3,4,5])

A         B         C         D         E
1  0.586263  0.780104  0.800207  0.237086  0.032342
2  0.773708  0.919960  0.189009  0.628798  0.246529
3  0.002574  0.344096  0.465108  0.110283  0.359631
4  0.727956  0.819141  0.171473  0.336021  0.779878
5  0.655749  0.747873  0.235329  0.516155  0.259126

In [20]:
male_tuple = {'서울특별시': 4732755,
             '부산광역시': 1558618,
             '인천광역시': 1476813,
             '대구광역시': 1198815,
             '대전광역시': 734441,
             '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732755
부산광역시    1558618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [21]:
female_tuple = {'서울특별시': 495571,
             '부산광역시': 17358121,
             '인천광역시': 1470404,
             '대구광역시': 1229030,
             '대전광역시': 736559,
             '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시      495571
부산광역시    17358121
인천광역시     1470404
대구광역시     1229030
대전광역시      736559
광주광역시      734988
dtype: int64

In [22]:
korea_df = pd.DataFrame({'인구수':population,
                         '남자인구수':male,
                         '여자인구수':female})
korea_df

인구수    남자인구수     여자인구수
서울특별시  9706240  4732755    495571
부산광역시  1000200  1558618  17358121
인천광역시  1224320  1476813   1470404
대구광역시  2838490  1198815   1229030
대전광역시  1833340   734441    736559
광주광역시  1000020   720060    734988

In [23]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [24]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [25]:
korea_df['여자인구수']

서울특별시      495571
부산광역시    17358121
인천광역시     1470404
대구광역시     1229030
대전광역시      736559
광주광역시      734988
Name: 여자인구수, dtype: int64

In [26]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수     여자인구수
서울특별시  9706240  4732755    495571
부산광역시  1000200  1558618  17358121
인천광역시  1224320  1476813   1470404

### Index 객체


In [27]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [28]:
idx[1]

4

In [29]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [30]:
idx[-1::]

Int64Index([10], dtype='int64')

In [31]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [32]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [33]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 6, 5, 7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2)) #교집합
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2) #여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 6, 5, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -2, 1, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


<ipython-input-33-b1bd21f3c9a6>:7: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  print(idx1 & idx2)
<ipython-input-33-b1bd21f3c9a6>:9: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  print(idx1 | idx2)
<ipython-input-33-b1bd21f3c9a6>:12: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  print(idx1 ^ idx2) #여집합




---



## 인덱싱(Indexing)

In [34]:
s = pd.Series([0, 2.5, 0.5, 0.75, 1],
              index=['a','b','c','d','e'])
s

a    0.00
b    2.50
c    0.50
d    0.75
e    1.00
dtype: float64

In [35]:
s['a']

0.0

In [36]:
'b' in s

True

In [37]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [38]:
list(s.items())

[('a', 0.0), ('b', 2.5), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [39]:
s['f'] = 1.25
s

a    0.00
b    2.50
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [40]:
s['a':'d']

a    0.00
b    2.50
c    0.50
d    0.75
dtype: float64

In [41]:
s[0:4]

a    0.00
b    2.50
c    0.50
d    0.75
dtype: float64

In [42]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [43]:
s[['a', 'c', 'd']]

a    0.00
c    0.50
d    0.75
dtype: float64

### Series 인덱싱

In [44]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
              index=[1, 3, 5, 7, 9])

In [45]:
s[1]

'a'

In [46]:
s[2:4]

5    c
7    d
dtype: object

In [47]:
s.iloc[1] #int로 접근하여 0부터 시작

'b'

In [48]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [49]:
s.reindex(range(10)) #10개의 레인지 값을 인덱스로 하겠다는 의미

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [50]:
s.reindex(range(10), method='bfi11')

ValueError: ignored

### DataFrame 인덱싱


In [53]:
korea_df

인구수    남자인구수     여자인구수
서울특별시  9706240  4732755    495571
부산광역시  1000200  1558618  17358121
인천광역시  1224320  1476813   1470404
대구광역시  2838490  1198815   1229030
대전광역시  1833340   734441    736559
광주광역시  1000020   720060    734988

In [54]:
korea_df['남자인구수']

서울특별시    4732755
부산광역시    1558618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [55]:
korea_df.남자인구수

서울특별시    4732755
부산광역시    1558618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.여자인구수

서울특별시      495571
부산광역시    17358121
인천광역시     1470404
대구광역시     1229030
대전광역시      736559
광주광역시      734988
Name: 여자인구수, dtype: int64

In [57]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [58]:
korea_df.남여비율

서울특별시    955.010483
부산광역시      8.979186
인천광역시    100.435867
대구광역시     97.541557
대전광역시     99.712447
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [59]:
korea_df.values

array([[9.70624000e+06, 4.73275500e+06, 4.95571000e+05, 9.55010483e+02],
       [1.00020000e+06, 1.55861800e+06, 1.73581210e+07, 8.97918617e+00],
       [1.22432000e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.83849000e+06, 1.19881500e+06, 1.22903000e+06, 9.75415572e+01],
       [1.83334000e+06, 7.34441000e+05, 7.36559000e+05, 9.97124467e+01],
       [1.00002000e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [60]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.706240e+06  1.000200e+06  1.224320e+06  2.838490e+06  1.833340e+06   
남자인구수  4.732755e+06  1.558618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.955710e+05  1.735812e+07  1.470404e+06  1.229030e+06  7.365590e+05   
남여비율   9.550105e+02  8.979186e+00  1.004359e+02  9.754156e+01  9.971245e+01   

              광주광역시  
인구수    1.000020e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [61]:
korea_df.values[0]

array([9.70624000e+06, 4.73275500e+06, 4.95571000e+05, 9.55010483e+02])

In [62]:
korea_df['인구수']

서울특별시    9706240
부산광역시    1000200
인천광역시    1224320
대구광역시    2838490
대전광역시    1833340
광주광역시    1000020
Name: 인구수, dtype: int64

In [63]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9706240  4732755
부산광역시  1000200  1558618
인천광역시  1224320  1476813

In [64]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수     여자인구수        남여비율
부산광역시  1000200  1558618  17358121    8.979186
인천광역시  1224320  1476813   1470404  100.435867
대구광역시  2838490  1198815   1229030   97.541557

In [65]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수    남자인구수     여자인구수        남여비율
부산광역시  1000200  1558618  17358121    8.979186
인천광역시  1224320  1476813   1470404  100.435867
대전광역시  1833340   734441    736559   99.712447
광주광역시  1000020   720060    734988   97.968946

In [66]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9706240  4732755   495571  955.010483
대구광역시  2838490  1198815  1229030   97.541557

In [67]:
korea_df.loc[(korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9706240  4732755   495571  955.010483
인천광역시  1224320  1476813  1470404  100.435867

In [68]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 > 100)]

인구수    남자인구수   여자인구수        남여비율
서울특별시  9706240  4732755  495571  955.010483

In [69]:
korea_df.iloc[:1, :2]

인구수    남자인구수
서울특별시  9706240  4732755

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [70]:
korea_df

인구수    남자인구수     여자인구수        남여비율
서울특별시  9706240  4732755    495571  955.010483
부산광역시  1000200  1558618  17358121    8.979186
인천광역시  1224320  1476813   1470404  100.435867
대구광역시  2838490  1198815   1229030   97.541557
대전광역시  1833340   734441    736559   99.712447
광주광역시  1000020   720060    734988   97.968946

In [71]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
              ('부산광역시', 2010), ('부산광역시', 2020),
              ('인천광역시', 2010), ('인천광역시', 2020),
              ('대구광역시', 2010), ('대구광역시', 2020),
              ('대전광역시', 2010), ('대전광역시', 2020),
              ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [72]:
pop_tuples = [10322545, 9720846, 
              3567910, 3404423, 
              2758296, 294727,
              2635472, 2427915,
              1503664, 1471040,
              1453636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10322545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     3567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)      294727
(대구광역시, 2010)     2635472
(대구광역시, 2020)     2427915
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1453636
(광주광역시, 2020)     1455048
dtype: int64

In [73]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [74]:
populaiton = population.reindex(midx)
population

(서울특별시, 2010)    10322545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     3567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)      294727
(대구광역시, 2010)     2635472
(대구광역시, 2020)     2427915
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1453636
(광주광역시, 2020)     1455048
dtype: int64

In [75]:
population = population.reindex(midx)
population

서울특별시  2010    10322545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020      294727
대구광역시  2010     2635472
       2020     2427915
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1453636
       2020     1455048
dtype: int64

In [76]:
population[:, 2010]

서울특별시    10322545
부산광역시     3567910
인천광역시     2758296
대구광역시     2635472
대전광역시     1503664
광주광역시     1453636
dtype: int64

In [77]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [78]:
korea_mdf = population.unstack() #다중인덱싱으로 만든 시리즈를 데이터 프레임으로 변환
korea_mdf

2010     2020
광주광역시   1453636  1455048
대구광역시   2635472  2427915
대전광역시   1503664  1471040
부산광역시   3567910  3404423
서울특별시  10322545  9720846
인천광역시   2758296   294727

In [79]:
korea_mdf.stack()

광주광역시  2010     1453636
       2020     1455048
대구광역시  2010     2635472
       2020     2427915
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     3567910
       2020     3404423
서울특별시  2010    10322545
       2020     9720846
인천광역시  2010     2758296
       2020      294727
dtype: int64

In [80]:
male_tuples = [5111259, 4732275,
              1773270, 1668618,
              1391248, 1476384,
              1255245, 1298815,
              7233648, 734441,
              721780, 729565]
male_tuples

[5111259,
 4732275,
 1773270,
 1668618,
 1391248,
 1476384,
 1255245,
 1298815,
 7233648,
 734441,
 721780,
 729565]

In [81]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10322545  5111259
      2020   9720846  4732275
부산광역시 2010   3567910  1773270
      2020   3404423  1668618
인천광역시 2010   2758296  1391248
      2020    294727  1476384
대구광역시 2010   2635472  1255245
      2020   2427915  1298815
대전광역시 2010   1503664  7233648
      2020   1471040   734441
광주광역시 2010   1453636   721780
      2020   1455048   729565

In [82]:
female_tuples = [5201286, 4988571,
                 1794735, 1735805,
                 1233553, 1473838,
                 1782953, 1734849,
                 128314, 738482,
                 734555, 734988]
female_tuples

[5201286,
 4988571,
 1794735,
 1735805,
 1233553,
 1473838,
 1782953,
 1734849,
 128314,
 738482,
 734555,
 734988]

In [83]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples})
korea_df

인구수    남자인구수     여자인구수        남여비율
서울특별시  9706240  4732755    495571  955.010483
부산광역시  1000200  1558618  17358121    8.979186
인천광역시  1224320  1476813   1470404  100.435867
대구광역시  2838490  1198815   1229030   97.541557
대전광역시  1833340   734441    736559   99.712447
광주광역시  1000020   720060    734988   97.968946

In [84]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010      98.269140
       2020      94.862336
부산광역시  2010      98.804002
       2020      96.129346
인천광역시  2010     112.783804
       2020     100.172746
대구광역시  2010      70.402585
       2020      74.866170
대전광역시  2010    5637.458111
       2020      99.452796
광주광역시  2010      98.260852
       2020      99.262165
dtype: float64

In [85]:
ratio.unstack()

2010        2020
광주광역시    98.260852   99.262165
대구광역시    70.402585   74.866170
대전광역시  5637.458111   99.452796
부산광역시    98.804002   96.129346
서울특별시    98.269140   94.862336
인천광역시   112.783804  100.172746

In [86]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_df

인구수    남자인구수     여자인구수        남여비율
서울특별시  9706240  4732755    495571  955.010483
부산광역시  1000200  1558618  17358121    8.979186
인천광역시  1224320  1476813   1470404  100.435867
대구광역시  2838490  1198815   1229030   97.541557
대전광역시  1833340   734441    736559   99.712447
광주광역시  1000020   720060    734988   97.968946

#### 다중 인덱스 생성

In [87]:
df = pd.DataFrame(np.random.rand(6, 3),
                  index=[['a', 'a', 'b','b','c','c'], [1, 2, 3, 2, 1, 2]],
                  columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.290304  0.291629  0.703284
  2  0.129336  0.755383  0.821759
b 3  0.786009  0.820515  0.800243
  2  0.585253  0.889640  0.899204
c 1  0.653735  0.371995  0.880285
  2  0.148057  0.403132  0.458750

In [88]:
pd.MultiIndex.from_arrays([['a', 'a', 'b','b','c','c'], [1, 2, 3, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 3),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex.from_arrays([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)])

MultiIndex([('a', 'a', 'b', 'b', 'c', 'c'),
            (  1,   2,   1,   2,   1,   2)],
           )

In [90]:
pd.MultiIndex.from_product([('a', 'b', 'c'), [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
pd.MultiIndex(levels=[('a', 'b', 'c'),(1, 2)],
                      codes=[(0, 0, 1, 1, 2, 2), (0, 1, 0, 1, 0, 1)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [92]:
population

서울특별시  2010    10322545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020      294727
대구광역시  2010     2635472
       2020     2427915
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1453636
       2020     1455048
dtype: int64

In [93]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10322545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
인천광역시  2010     2758296
       2020      294727
대구광역시  2010     2635472
       2020     2427915
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1453636
       2020     1455048
dtype: int64

In [94]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                 names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                   names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6,6), 2)
mdf = pd.DataFrame(data, index = idx, columns = cols )
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.16  0.74  0.68 -1.44 -1.09  0.91
      2      0.19 -0.10  0.54  0.33 -0.66  0.28
b     1      0.10  2.28 -0.35  1.21  2.10 -0.01
      2     -1.13  1.84  0.58 -0.90  1.05  0.24
c     1     -0.35 -1.21  0.79  0.44 -1.16  0.21
      2     -0.49  0.06  1.31 -0.47  0.24 -1.33

In [95]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1      0.68 -1.44
      2      0.54  0.33
b     1     -0.35  1.21
      2      0.58 -0.90
c     1      0.79  0.44
      2      1.31 -0.47

#### 인덱싱 및 슬라이싱

In [96]:
population['인천광역시', 2010]

2758296

In [97]:
population[:, 2010]

행정구역
서울특별시    10322545
부산광역시     3567910
인천광역시     2758296
대구광역시     2635472
대전광역시     1503664
광주광역시     1453636
dtype: int64

In [98]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10322545
       2020     9720846
부산광역시  2010     3567910
       2020     3404423
dtype: int64

In [99]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2635472
       2020    2427915
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [101]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.16  0.74  0.68 -1.44 -1.09  0.91
      2      0.19 -0.10  0.54  0.33 -0.66  0.28
b     1      0.10  2.28 -0.35  1.21  2.10 -0.01
      2     -1.13  1.84  0.58 -0.90  1.05  0.24
c     1     -0.35 -1.21  0.79  0.44 -1.16  0.21
      2     -0.49  0.06  1.31 -0.47  0.24 -1.33

In [103]:
mdf['c2', 1]

name1  name2
a      1        0.68
       2        0.54
b      1       -0.35
       2        0.58
c      1        0.79
       2        1.31
Name: (c2, 1), dtype: float64

In [104]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -0.16  0.74  0.68 -1.44
      2      0.19 -0.10  0.54  0.33
b     1      0.10  2.28 -0.35  1.21

In [106]:
mdf.loc[:, {'c2':1}]

col_name1      c2      
col_name2       1     2
name1 name2            
a     1      0.68 -1.44
      2      0.54  0.33
b     1     -0.35  1.21
      2      0.58 -0.90
c     1      0.79  0.44
      2      1.31 -0.47

In [110]:
idx_slice = pd.IndexSlice
mdf.loc[[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.10  0.33  0.28
b     2      1.84 -0.90  0.24
c     2      0.06 -0.47 -1.33

#### 다중 인덱스 재정렬

In [111]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [112]:
korea_mdf

총인구수    남자인구수    여자인구수         남여비율
행정구역  년도                                           
서울특별시 2010  10322545  5111259  5201286    98.269140
      2020   9720846  4732275  4988571    94.862336
부산광역시 2010   3567910  1773270  1794735    98.804002
      2020   3404423  1668618  1735805    96.129346
인천광역시 2010   2758296  1391248  1233553   112.783804
      2020    294727  1476384  1473838   100.172746
대구광역시 2010   2635472  1255245  1782953    70.402585
      2020   2427915  1298815  1734849    74.866170
대전광역시 2010   1503664  7233648   128314  5637.458111
      2020   1471040   734441   738482    99.452796
광주광역시 2010   1453636   721780   734555    98.260852
      2020   1455048   729565   734988    99.262165

In [114]:
#korea_mdf('서울특별시':'인천광역시') #정렬이 안되서 오\ㅔ러러
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수         남여비율
행정구역  년도                                           
광주광역시 2010   1453636   721780   734555    98.260852
      2020   1455048   729565   734988    99.262165
대구광역시 2010   2635472  1255245  1782953    70.402585
      2020   2427915  1298815  1734849    74.866170
대전광역시 2010   1503664  7233648   128314  5637.458111
      2020   1471040   734441   738482    99.452796
부산광역시 2010   3567910  1773270  1794735    98.804002
      2020   3404423  1668618  1735805    96.129346
서울특별시 2010  10322545  5111259  5201286    98.269140
      2020   9720846  4732275  4988571    94.862336
인천광역시 2010   2758296  1391248  1233553   112.783804
      2020    294727  1476384  1473838   100.172746

In [115]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10322545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1391248  1233553  112.783804
      2020    294727  1476384  1473838  100.172746

In [116]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1453636  2635472  1503664  3567910  10322545  2758296  721780  1255245   
2020  1455048  2427915  1471040  3404423   9720846   294727  729565  1298815   

                        ...   여자인구수                                  남여비율  \
행정구역    대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                      ...                                                 
2010  7233648  1773270  ...  128314  1794735  5201286  1233553  98.260852   
2020   734441  1668618  ...  738482  1735805  4988571  1473838  99.262165   

                                                                
행정구역      대구광역시        대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                              
2010  70.402585  5637.458111  98.804002  98.269140  112.783804  
2020  74.866170    99.452796  96.129346  94.862336  100.172746  

[2 rows x 24 columns]

In [117]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                  남여비율  \
년도         2010     2020     2010     2020     2010     2020         2010   
행정구역                                                                        
광주광역시   1453636  1455048   721780   729565   734555   734988    98.260852   
대구광역시   2635472  2427915  1255245  1298815  1782953  1734849    70.402585   
대전광역시   1503664  1471040  7233648   734441   128314   738482  5637.458111   
부산광역시   3567910  3404423  1773270  1668618  1794735  1735805    98.804002   
서울특별시  10322545  9720846  5111259  4732275  5201286  4988571    98.269140   
인천광역시   2758296   294727  1391248  1476384  1233553  1473838   112.783804   

                   
년도           2020  
행정구역               
광주광역시   99.262165  
대구광역시   74.866170  
대전광역시   99.452796  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.172746

In [118]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.453636e+06
             남자인구수    7.217800e+05
             여자인구수    7.345550e+05
             남여비율     9.826085e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.295650e+05
             여자인구수    7.349880e+05
             남여비율     9.926216e+01
대구광역시  2010  총인구수     2.635472e+06
             남자인구수    1.255245e+06
             여자인구수    1.782953e+06
             남여비율     7.040258e+01
       2020  총인구수     2.427915e+06
             남자인구수    1.298815e+06
             여자인구수    1.734849e+06
             남여비율     7.486617e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.233648e+06
             여자인구수    1.283140e+05
             남여비율     5.637458e+03
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.384820e+05
             남여비율     9.945280e+01
부산광역시  2010  총인구수     3.567910e+06
             남자인구수    1.773270e+06
             여자인구수    1.794735e+06
             남여비율     9.880400e+01
 

In [119]:
korea_mdf

총인구수    남자인구수    여자인구수         남여비율
행정구역  년도                                           
광주광역시 2010   1453636   721780   734555    98.260852
      2020   1455048   729565   734988    99.262165
대구광역시 2010   2635472  1255245  1782953    70.402585
      2020   2427915  1298815  1734849    74.866170
대전광역시 2010   1503664  7233648   128314  5637.458111
      2020   1471040   734441   738482    99.452796
부산광역시 2010   3567910  1773270  1794735    98.804002
      2020   3404423  1668618  1735805    96.129346
서울특별시 2010  10322545  5111259  5201286    98.269140
      2020   9720846  4732275  4988571    94.862336
인천광역시 2010   2758296  1391248  1233553   112.783804
      2020    294727  1476384  1473838   100.172746

In [120]:
idx_flat= korea_mdf.reset_index(level=0)
idx_flat #연도별로 떨어진 형태로 나옴

행정구역      총인구수    남자인구수    여자인구수         남여비율
년도                                                  
2010  광주광역시   1453636   721780   734555    98.260852
2020  광주광역시   1455048   729565   734988    99.262165
2010  대구광역시   2635472  1255245  1782953    70.402585
2020  대구광역시   2427915  1298815  1734849    74.866170
2010  대전광역시   1503664  7233648   128314  5637.458111
2020  대전광역시   1471040   734441   738482    99.452796
2010  부산광역시   3567910  1773270  1794735    98.804002
2020  부산광역시   3404423  1668618  1735805    96.129346
2010  서울특별시  10322545  5111259  5201286    98.269140
2020  서울특별시   9720846  4732275  4988571    94.862336
2010  인천광역시   2758296  1391248  1233553   112.783804
2020  인천광역시    294727  1476384  1473838   100.172746

In [122]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수         남여비율
0   광주광역시  2010   1453636   721780   734555    98.260852
1   광주광역시  2020   1455048   729565   734988    99.262165
2   대구광역시  2010   2635472  1255245  1782953    70.402585
3   대구광역시  2020   2427915  1298815  1734849    74.866170
4   대전광역시  2010   1503664  7233648   128314  5637.458111
5   대전광역시  2020   1471040   734441   738482    99.452796
6   부산광역시  2010   3567910  1773270  1794735    98.804002
7   부산광역시  2020   3404423  1668618  1735805    96.129346
8   서울특별시  2010  10322545  5111259  5201286    98.269140
9   서울특별시  2020   9720846  4732275  4988571    94.862336
10  인천광역시  2010   2758296  1391248  1233553   112.783804
11  인천광역시  2020    294727  1476384  1473838   100.172746

In [125]:
idx_flat.set_index(['행정구역','년도'])

총인구수    남자인구수    여자인구수         남여비율
행정구역  년도                                           
광주광역시 2010   1453636   721780   734555    98.260852
      2020   1455048   729565   734988    99.262165
대구광역시 2010   2635472  1255245  1782953    70.402585
      2020   2427915  1298815  1734849    74.866170
대전광역시 2010   1503664  7233648   128314  5637.458111
      2020   1471040   734441   738482    99.452796
부산광역시 2010   3567910  1773270  1794735    98.804002
      2020   3404423  1668618  1735805    96.129346
서울특별시 2010  10322545  5111259  5201286    98.269140
      2020   9720846  4732275  4988571    94.862336
인천광역시 2010   2758296  1391248  1233553   112.783804
      2020    294727  1476384  1473838   100.172746

## 데이터 연산

In [127]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    7
1    5
2    9
3    3
4    5
dtype: int64

In [128]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns=['A', 'B', 'C'])
df

A  B  C
0  1  0  6
1  6  5  1
2  2  1  2

In [129]:
np.exp(s)

0    1096.633158
1     148.413159
2    8103.083928
3      20.085537
4     148.413159
dtype: float64

In [130]:
np.cos(df * np.pi / 4)

A         B             C
0  7.071068e-01  1.000000 -1.836970e-16
1 -1.836970e-16 -0.707107  7.071068e-01
2  6.123234e-17  0.707107  6.123234e-17

In [131]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1,2,3,4,5])
s1 + s2


0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [134]:
s1.add(s2, fill_value=0) #nan대신 0이들어감

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [142]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                   columns=list('ACD'))
df1

A   C   D
0  1  15   3
1  3   2   1
2  8  19  15

In [143]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                   columns=list('BAACD'))
df2

B   A   A   C   D
0  18   6  13   5   0
1   4  11  11  15  10
2   8   6   3  18   2
3  18   9   7  17   9
4   4  19  15   7   0

In [144]:
df1 + df2

A     A   B     C     D
0   7.0  14.0 NaN  20.0   3.0
1  14.0  14.0 NaN  17.0  11.0
2  14.0  11.0 NaN  37.0  17.0
3   NaN   NaN NaN   NaN   NaN
4   NaN   NaN NaN   NaN   NaN

In [147]:
fvalue = df1.stack().mean()
df.add(df2, fill_value = fvalue)

A          A          B          C          D
0   7.000000  14.000000  18.000000  11.000000   7.444444
1  17.000000  17.000000   9.000000  16.000000  17.444444
2   8.000000   5.000000   9.000000  20.000000   9.444444
3  16.444444  14.444444  25.444444  24.444444  16.444444
4  26.444444  22.444444  11.444444  14.444444   7.444444

### 연산자 범용 함수


#### add()

In [149]:
a = np.random.randint(1, 10, (3,3))
a

array([[8, 1, 9],
       [9, 4, 3],
       [2, 3, 1]])

In [150]:
a + a[0]

array([[16,  2, 18],
       [17,  5, 12],
       [10,  4, 10]])

In [191]:
df = pd.DataFrame(a, columns = list('ABC'))
df

A  B  C
0  8  1  9
1  9  4  3
2  2  3  1

In [193]:
df = df.iloc[0]
df

8

In [154]:
df.add(df.iloc[0])

A    16
B     9
C    17
Name: 0, dtype: int64

#### sub() / subtract()

In [155]:
a

array([[8, 1, 9],
       [9, 4, 3],
       [2, 3, 1]])

In [156]:
a + a[0]

array([[16,  2, 18],
       [17,  5, 12],
       [10,  4, 10]])

In [157]:
df + df.iloc[0]

A    16
B     9
C    17
Name: 0, dtype: int64

In [158]:
df.sub(df.iloc[0])

A    0
B   -7
C    1
Name: 0, dtype: int64

In [163]:
df.subtract(df['B'], axis=0)

A    7
B    0
C    8
Name: 0, dtype: int64

#### mul() / multply()




In [165]:
a

array([[8, 1, 9],
       [9, 4, 3],
       [2, 3, 1]])

In [166]:
a + a[0]

array([[16,  2, 18],
       [17,  5, 12],
       [10,  4, 10]])

In [167]:
df

A    8
B    1
C    9
Name: 0, dtype: int64

In [164]:
df + df.iloc[0]

A    16
B     9
C    17
Name: 0, dtype: int64

In [169]:
df.mul(df.iloc[1])

A    8
B    1
C    9
Name: 0, dtype: int64

In [170]:
df.multiply(df.iloc[2])

A    72
B     9
C    81
Name: 0, dtype: int64

#### truediv() /  div() / divide() / floordiv()

In [171]:
a

array([[8, 1, 9],
       [9, 4, 3],
       [2, 3, 1]])

In [172]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.125     , 4.        , 0.33333333],
       [0.25      , 3.        , 0.11111111]])

In [173]:
df

A    8
B    1
C    9
Name: 0, dtype: int64

In [174]:
df / df.iloc[0]

A    1.000
B    0.125
C    1.125
Name: 0, dtype: float64

In [175]:
df.truediv(df.iloc[0])

A    1.000
B    0.125
C    1.125
Name: 0, dtype: float64

In [176]:
df.div(df.iloc[1])

A    8.0
B    1.0
C    9.0
Name: 0, dtype: float64

In [177]:
df.divide(df.iloc[2])

A    0.888889
B    0.111111
C    1.000000
Name: 0, dtype: float64

In [178]:
a // a[0]

array([[1, 1, 1],
       [1, 4, 0],
       [0, 3, 0]])

In [180]:
df.floordiv(df.iloc[0])

A    1
B    0
C    1
Name: 0, dtype: int64

#### mod()

In [181]:
a

array([[8, 1, 9],
       [9, 4, 3],
       [2, 3, 1]])

In [182]:
a % a[0]

array([[0, 0, 0],
       [1, 0, 3],
       [2, 0, 1]])

In [183]:
df

A    8
B    1
C    9
Name: 0, dtype: int64

In [184]:
df.mod(df.iloc[0])

A    0
B    1
C    1
Name: 0, dtype: int64

#### pow()

In [185]:
a

array([[8, 1, 9],
       [9, 4, 3],
       [2, 3, 1]])

In [186]:
a ** a[0]

array([[ 16777216,         1, 387420489],
       [ 43046721,         4,     19683],
       [      256,         3,         1]])

In [187]:
df

A    8
B    1
C    9
Name: 0, dtype: int64

In [188]:
df.pow(df.iloc[0])

A    16777216
B           1
C    43046721
Name: 0, dtype: int64

In [194]:
row = df.iloc[0, ::2]
row

AttributeError: ignored

### 정렬(Sort)

In [197]:
s = pd.Series(range(5), index=['A', 'B', 'B', 'C', 'E'])
s

A    0
B    1
B    2
C    3
E    4
dtype: int64

In [198]:
s.sort_index()

A    0
B    1
B    2
C    3
E    4
dtype: int64

In [199]:
s.sort_values()

A    0
B    1
B    2
C    3
E    4
dtype: int64

In [220]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                  index = [2, 4, 1, 3],
                  columns = list('BDAC'))
df

B  D  A  C
2  8  0  3  7
4  5  9  9  1
1  5  6  1  5
3  5  2  6  4

In [222]:
df.sort_index()

B  D  A  C
1  5  6  1  5
2  8  0  3  7
3  5  2  6  4
4  5  9  9  1

In [223]:
df.sort_values(by='A')

B  D  A  C
1  5  6  1  5
2  8  0  3  7
3  5  2  6  4
4  5  9  9  1

In [224]:
df.sort_values(by=['A', 'C'])

B  D  A  C
1  5  6  1  5
2  8  0  3  7
3  5  2  6  4
4  5  9  9  1

In [225]:
df.sort_index(axis=1) #축을 기준으로로

A  B  C  D
2  3  8  7  0
4  9  5  1  9
1  1  5  5  6
3  6  5  4  2

### 순위(Ranking)


In [226]:
s = pd.Series([-2, 4, 5, 6, 2, -4, 0, -6, 2, 1])
s

0   -2
1    4
2    5
3    6
4    2
5   -4
6    0
7   -6
8    2
9    1
dtype: int64

In [227]:
s.rank()

0     3.0
1     8.0
2     9.0
3    10.0
4     6.5
5     2.0
6     4.0
7     1.0
8     6.5
9     5.0
dtype: float64

In [229]:
s.rank(method='first')

0     3.0
1     8.0
2     9.0
3    10.0
4     6.0
5     2.0
6     4.0
7     1.0
8     7.0
9     5.0
dtype: float64

In [230]:
s.rank(method='max')

0     3.0
1     8.0
2     9.0
3    10.0
4     7.0
5     2.0
6     4.0
7     1.0
8     7.0
9     5.0
dtype: float64

### 고성능 연산

In [233]:
nrows, ncol = 10000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncol)) for i in range(4))

In [234]:
%timeit df1 + df2 + df3 + df4

13.2 ms ± 1.51 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [235]:
%timeit pd.eval('df1 +df2 +df3 + df4')

6.12 ms ± 512 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [236]:
%timeit df1 + -df2 / (df3 * df4)

17.3 ms ± 3.52 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [239]:
%timeit pd.eval('df1 * -df2 / (df3 * df4)')

17.4 ms ± 3.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [241]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

6.98 ms ± 900 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [242]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

15.2 ms ± 3.13 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [244]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A', 'B', 'C', 'D', 'E'])
df.head()

A         B         C         D         E
0  0.896181  0.311272  0.164702  0.519797  0.670043
1  0.992760  0.416164  0.667618  0.157256  0.085290
2  0.885533  0.843476  0.673815  0.884402  0.754265
3  0.154852  0.193752  0.025631  0.894206  0.135837
4  0.025499  0.241311  0.780323  0.961601  0.938955

In [245]:
%timeit df['A'] + df['B'] / df['C'] - df['E']

24 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [246]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

20.1 ms ± 4.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [251]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.896181  0.311272  0.164702  0.519797  0.670043  2.437805
1  0.992760  0.416164  0.667618  0.157256  0.085290  1.602705
2  0.885533  0.843476  0.673815  0.884402  0.754265  1.470251
3  0.154852  0.193752  0.025631  0.894206  0.135837  7.592683
4  0.025499  0.241311  0.780323  0.961601  0.938955 -0.568156

In [252]:
df.eval('R = A - B / C + D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.896181  0.311272  0.164702  0.519797  0.670043 -0.645442
1  0.992760  0.416164  0.667618  0.157256  0.085290  0.382815
2  0.885533  0.843476  0.673815  0.884402  0.754265  0.300815
3  0.154852  0.193752  0.025631  0.894206  0.135837 -7.282979
4  0.025499  0.241311  0.780323  0.961601  0.938955  0.619154

In [254]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.215607
1         1.443077
2         1.609250
3        -0.824931
4         0.619973
            ...   
999995    0.755288
999996    0.751192
999997    1.263067
999998    0.519276
999999    0.283683
Length: 1000000, dtype: float64

In [256]:
df.eval('A +@col_mean') #외부변수 호출 시

0         1.215607
1         1.443077
2         1.609250
3        -0.824931
4         0.619973
            ...   
999995    0.755288
999996    0.751192
999997    1.263067
999998    0.519276
999999    0.283683
Length: 1000000, dtype: float64

In [257]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
4       0.025499  0.241311  0.780323  0.961601  0.938955  0.619154
25      0.477743  0.040739  0.699402  0.225014  0.534922  0.539860
30      0.350749  0.442839  0.953757  0.680199  0.915956  0.509472
31      0.110915  0.200420  0.521639  0.052756  0.586103 -0.242376
37      0.411576  0.361431  0.928718  0.482076  0.386107  0.208536
...          ...       ...       ...       ...       ...       ...
999968  0.382294  0.220921  0.996514  0.188073  0.015755  0.163563
999980  0.401915  0.100984  0.533346  0.037418  0.707137  0.239034
999988  0.339379  0.028071  0.876874  0.119257  0.800971  0.402888
999989  0.380124  0.317980  0.819168  0.659810  0.099613  0.057675
999994  0.414343  0.353405  0.579837  0.581571  0.704542  0.214594

[124985 rows x 6 columns]

In [258]:
pd.eval('(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)')

0         False
1         False
2         False
3         False
4          True
          ...  
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [267]:
df.query('A < 0.5 and B < 0.5 and C > 0.5')

A         B         C         D         E         R
4       0.025499  0.241311  0.780323  0.961601  0.938955  0.619154
25      0.477743  0.040739  0.699402  0.225014  0.534922  0.539860
30      0.350749  0.442839  0.953757  0.680199  0.915956  0.509472
31      0.110915  0.200420  0.521639  0.052756  0.586103 -0.242376
37      0.411576  0.361431  0.928718  0.482076  0.386107  0.208536
...          ...       ...       ...       ...       ...       ...
999968  0.382294  0.220921  0.996514  0.188073  0.015755  0.163563
999980  0.401915  0.100984  0.533346  0.037418  0.707137  0.239034
999988  0.339379  0.028071  0.876874  0.119257  0.800971  0.402888
999989  0.380124  0.317980  0.819168  0.659810  0.099613  0.057675
999994  0.414343  0.353405  0.579837  0.581571  0.704542  0.214594

[124985 rows x 6 columns]

In [260]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E          R
3       0.154852  0.193752  0.025631  0.894206  0.135837  -7.282979
4       0.025499  0.241311  0.780323  0.961601  0.938955   0.619154
5       0.260386  0.397128  0.394006  0.619746  0.865068  -0.211414
6       0.379070  0.396506  0.307263  0.750833  0.990016  -0.168037
13      0.443564  0.411315  0.010577  0.716247  0.185239 -38.310312
...          ...       ...       ...       ...       ...        ...
999985  0.412184  0.147716  0.143844  0.571677  0.691082  -0.219662
999988  0.339379  0.028071  0.876874  0.119257  0.800971   0.402888
999989  0.380124  0.317980  0.819168  0.659810  0.099613   0.057675
999994  0.414343  0.353405  0.579837  0.581571  0.704542   0.214594
999999  0.273592  0.227961  0.191785  0.101075  0.164543  -0.898406

[249325 rows x 6 columns]

In [262]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E          R
3       0.154852  0.193752  0.025631  0.894206  0.135837  -7.282979
4       0.025499  0.241311  0.780323  0.961601  0.938955   0.619154
5       0.260386  0.397128  0.394006  0.619746  0.865068  -0.211414
6       0.379070  0.396506  0.307263  0.750833  0.990016  -0.168037
13      0.443564  0.411315  0.010577  0.716247  0.185239 -38.310312
...          ...       ...       ...       ...       ...        ...
999985  0.412184  0.147716  0.143844  0.571677  0.691082  -0.219662
999988  0.339379  0.028071  0.876874  0.119257  0.800971   0.402888
999989  0.380124  0.317980  0.819168  0.659810  0.099613   0.057675
999994  0.414343  0.353405  0.579837  0.581571  0.704542   0.214594
999999  0.273592  0.227961  0.191785  0.101075  0.164543  -0.898406

[249325 rows x 6 columns]

In [50]:
#고성능 연산 메소드 = eval, query

## 데이터 결합

### Concat() / Append()

In [271]:
s1 = pd.Series(['a', 'b'], index = [1, 2])
s2 = pd.Series(['c', 'd'], index = [3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [273]:
def create_df(cols, idx):
  data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
  return pd.DataFrame(data, idx)

In [275]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [276]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [277]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [278]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [279]:
df4 = create_df('CD', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [280]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly